// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MyDummyEnum = "One" | { "Two": string } | { "Three": { Ok : number } | { Err : string } } | { "Four": boolean | null };
