// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MyDummyEnum } from "./MyDummyEnum.ts";

export type MyDummyStruct = { id: number, label: string, values: Array<number>, enumeration: MyDummyEnum, };
